<?php
/**
 * ForecastApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Okaufmann\WeatherApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Temperature
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Okaufmann\WeatherApiClient;

use \Okaufmann\WeatherApiClient\Configuration;
use \Okaufmann\WeatherApiClient\ApiClient;
use \Okaufmann\WeatherApiClient\ApiException;
use \Okaufmann\WeatherApiClient\ObjectSerializer;

/**
 * ForecastApiTest Class Doc Comment
 *
 * @category Class
 * @package  Okaufmann\WeatherApiClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ForecastApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for forecastPostalCodeRainfallGet
     *
     * .
     *
     */
    public function testForecastPostalCodeRainfallGet()
    {
    }

    /**
     * Test case for forecastPostalCodeTemperatureGet
     *
     * .
     *
     */
    public function testForecastPostalCodeTemperatureGet()
    {
    }

    /**
     * Test case for locationsGet
     *
     * .
     *
     */
    public function testLocationsGet()
    {
    }

    /**
     * Test case for locationsLocationIdGet
     *
     * .
     *
     */
    public function testLocationsLocationIdGet()
    {
    }
}
